# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import streamPOC_pb2 as streamPOC__pb2


class StreamPOCserviceStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.requestData = channel.unary_stream(
        '/streamPOC.StreamPOCservice/requestData',
        request_serializer=streamPOC__pb2.streamRequest.SerializeToString,
        response_deserializer=streamPOC__pb2.numberReply.FromString,
        )


class StreamPOCserviceServicer(object):
  """The greeting service definition.
  """

  def requestData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StreamPOCserviceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'requestData': grpc.unary_stream_rpc_method_handler(
          servicer.requestData,
          request_deserializer=streamPOC__pb2.streamRequest.FromString,
          response_serializer=streamPOC__pb2.numberReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'streamPOC.StreamPOCservice', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
